#######################################################################
# PGE configuration for L2_RTC_S1.
#######################################################################

# The runconfig section is intended to be used for dynamically generating the runconfig file used
# when running the OPERA PGEs. Any values set with a "__CHIMERA_VAL__" should be filled in by the input
# preprocessor. Otherwise, a precondition evaluation error will be raised by chimera.
#
# The runconfig section is also used as the data dict for the RunConfig jinja2 template.
# Accordingly, the schema here does NOT need to match the final RunConfig.yaml schema.
#
# * See RunConfig_schema.<label>.yaml for RunConfig.yaml documentation.
# * See related `RunConfig.yaml.<label>.jinja2.tmpl` file
#  and `util.conf_util.RunConfig.__init__()` for jinja2 usage.
runconfig:
  input_file_group:
    safe_file_path: __CHIMERA_VAL__
    orbit_file_path: __CHIMERA_VAL__
  dynamic_ancillary_file_group:
    dem_file: __CHIMERA_VAL__
  product_path_group:
    product_version: __CHIMERA_VAL__
    product_path: /home/rtc_user/output_dir
    # Scratch path is defined relative to output_dir to avoid file system permission issues
    scratch_path: /home/rtc_user/output_dir/scratch_dir
  cnm_version: "__CHIMERA_VAL__"

# This lists all the precondition evaluation steps that this PGE needs to run prior to running the PGE.
preconditions:
  - get_product_version
  - get_slc_s1_safe_file
  - get_slc_s1_orbit_file
  - get_slc_s1_dem  # Note: this must be run after get_slc_s1_safe_file
  - get_cnm_version
  - set_daac_product_type

# This lists all the postprocessor steps that this PGE will run after running the PGE.
postprocess:
  - update_product_accountability

get_product_version:
  version_key: "RTC_S1_PRODUCT_VERSION"

get_slc_s1_orbit_file:
  # TODO: use the sample orbit file provided by ADT until the stage_orbit_file.py
  #       script is integrated with the download job for SLC products
  s3_bucket: "opera-dev-lts-fwd-collinss"
  s3_key: "S1A_OPER_AUX_POEORB_OPOD_20220521T081912_V20220430T225942_20220502T005942.EOF"

get_slc_s1_dem:
  # The s3 bucket containing the global DEM(s) to download regions from
  s3_bucket: "opera-dem"

set_daac_product_type:
  template: OPERA_L2_CSLC_S1_{cnm_version}

# This function will add to the PGE output metadata when product to dataset conversion is performed
set_extra_pge_output_metadata:
   daac_product_type: daac_product_type

# List the extensions that the PGE generates
output_types:
  L2_CSLC:
    - nc  # TODO: this will change to geotiff for future SAS versions
    - catalog.json
    - iso.xml
    - log
    - qa.log

# The PGE name
# This must MATCH the corresponding entry in pge_outputs.yaml
pge_name: "L2_RTC_S1"

# Set the primary input/output types here
primary_input: "L1_S1_SLC"
primary_output: "L2_RTC_S1"

# List the groups that Chimera will need to localize
# The entries MUST reference a property of `$.runconfig` of this YAML.
# The referenced properties MUST be maps.
localize_groups:
  - input_file_group
  - dynamic_ancillary_file_group


#######################################################################
# PGE Simulation Mode
#
# * See PGE_SIMULATION_MODE in settings.yaml and it's usage
# * See SIMULATE_OUTPUTS usage in opera_pge_wrapper.py and chimera.precondition_evaluator.py
#######################################################################
input_file_base_name_regexes: # regexes taken from settings.yaml
    - '(?P<mission_id>S1A|S1B)_(?P<beam_mode>IW)_(?P<product_type>SLC)(?P<resolution>_)_(?P<level>1)(?P<class>S)(?P<pol>SH|SV|DH|DV)_(?P<start_ts>(?P<start_year>\d{4})(?P<start_month>\d{2})(?P<start_day>\d{2})T(?P<start_hour>\d{2})(?P<start_minute>\d{2})(?P<start_second>\d{2}))_(?P<stop_ts>(?P<stop_year>\d{4})(?P<stop_month>\d{2})(?P<stop_day>\d{2})T(?P<stop_hour>\d{2})(?P<stop_minute>\d{2})(?P<stop_second>\d{2}))_(?P<orbit_num>\d{6})_(?P<data_take_id>[0-9A-F]{6})_(?P<product_id>[0-9A-F]{4})$'
output_base_name: OPERA_L2_RTC_S1_{burst_id}_{acquisition_ts}Z_{creation_ts}Z_{sensor}_30_{product_version}
ancillary_base_name: OPERA_L2_RTC_S1_{creation_ts}Z_{sensor}_30_{product_version}
